### ISSUE TITLE
Multiline comment color does not persist on use of => in the comment

### ISSUE THREAD

**Issue by aa8y** [derekwyatt/vim-scala#100]
When I use an arrow in the comment, its blue color does not persist.

![comcolor](https://cloud.githubusercontent.com/assets/5642392/6320220/c5761140-ba95-11e4-9b68-1ba7bb4b9d7b.png)

I don't know if it's a problem with my `vim` or a bug in the plugin.

**Comment by derekwyatt** [comment]
Nope, this is a bug with the plugin.  We're including HTML in comments with the `html` syntax file, and a lone `>` is an error, which screws up everything that follows.

Does anyone else have any thoughts here?  I'm happy to remove the HTML but I'm betting I'm in the minority.

**Comment by slothspot** [comment]
Hi. Faced this problem recently. For myself, I removed `@scalaHtml` from `scalaMultilineComment`.
I would vote for removing of HTML from Scala highlight definition or make it optional. Another approach, as I understand, is to modify HTML highlight definition itself.

**Comment by henrytill** [comment]
:+1: for removing `@scalaHtml` from `scalaMultilineComment`

**Comment by derekwyatt** [comment]
@ches Whatdya think?  I'm all for tossing it.

**Comment by aa8y** [comment]
Any updates on this?

**Comment by ches** [comment]
I'm not particularly attached to the HTML embedding. If someone feels strongly about wanting it back, perhaps they can try to figure a way to write the syntax definition that works around this issue.

**Comment by derekwyatt** [comment]
I'm all for ripping it out.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Ches MartinSent: Monday, February 1, 2016 8:52 AMTo: derekwyatt/vim-scalaReply To: derekwyatt/vim-scalaCc: Derek WyattSubject: Re: [vim-scala] Multiline comment color does not persist on use of => in the comment (#100)I'm not particularly attached to the HTML embedding. If someone feels strongly about wanting it back, perhaps they can try to figure a way to write the syntax definition that works around this issue.

—Reply to this email directly or view it on GitHub.

**Comment by henrytill** [comment]
I opened a PR to remove it: #121
