### ISSUE TITLE
Loosing syntax highlighting when flipping buffers 

### ISSUE THREAD

**Issue by maxMidius** [derekwyatt/vim-scala#108]
Hi - Firstly thanks for this nice plugin 
When I first launch  vim <somefile.scala>    it shows the syntax highlighting 
However if I flip to another scala file  it looses its colors
If I do :  set filetype=scala  in the new buffer  the colors become visible.
What am I missing here ?

My .vimrc  file looks like this 
    5 set ai
    6 set sw=4
    7 set nowrap
    8 set incsearch
    9 set hlsearch
   10 set guifont=Liberation\ Mono\ 10
   11 set nobackup
   12 set ruler
   13 set nu
   14 set fileformat=unix
   15 highlight search ctermfg=12 ctermbg=3
   16 highlight Identifier ctermfg=4
   17 highlight Statement ctermfg=5
   18 filetype plugin on
   19 let g:pydiction_location = '~/.vim/plugin/complete-dict'
   20 set tags=tags,./tags,$PROJTOP/tags
   21 "autocmd BufEnter * if expand("%:p:h") !~ '^/tmp' | lcd %:p:h | endif
   22 set autochdir
   23 colorscheme  murphy
   24 syntax on

**Comment by derekwyatt** [comment]
It looks like the installation of the plugin in, somehow, wrong.  It's not clear how it's installed from your `.vimrc`, but regardless there's gotta be something wrong there.  The recommended way to install is to use a package manager - I use `Vundle` currently, and it works great - so you should switch to one of those.  If you're going to "roll your own" then you're "on your own" :)
