### ISSUE TITLE
Pathogen Install

### ISSUE THREAD

**Issue by allcentury** [derekwyatt/vim-scala#110]
I've cloned this repo into my `~/.vim/bundle` folder just like all other plugins (you can [see my dotfiles](https://github.com/allcentury/dotfiles)) but alas no plugin is detected.  I've tried just a few of the basic commands (ie `SortScalaImports`) without luck.  

In addition to cloning am I required to also run the wget/curl command or am I missing something painstakingly obvious?

**Comment by derekwyatt** [comment]
I don't know what to tell you... it's not this plugin's fault, that's 
for certain :)

Are you sure you re-sourced your ~/.vimrc? Have you got pathogen set up 
properly?

Anthony Ross wrote:

**Comment by allcentury** [comment]
After running the command-line instructions it's working now.  I guess I'm still unsure if that's part of the installation instructions with pathogen but I'm guessing not.
