### ISSUE TITLE
Autogenerating multilined comments

### ISSUE THREAD

**Issue by hlin117** [derekwyatt/vim-scala#112]
It would be nice if when you typed
```
/**<cursor here>
```
And then a `newline`, the multilined comment would continue to build to be
```
/**
  * <cursor here>
```
And then another newline would create another ` * ` string on the line
```
/**
  * 
  * <cursor here>
```
Finally, a `/` character would cease the mutilined comment:
```
/**
  * 
  */<cursor here, one space was removed>
```
I think this is default vim behavior for C++ files.

I'm basing these kinds of comments off of the scala wikipedia <a href="https://wiki.scala-lang.org/display/SW/Syntax">here</a>.

**Comment by derekwyatt** [comment]
That's what it should be doing by default.  Seems like you're altering the `formatoptions` setting.  What do you have it set to?

**Comment by hlin117** [comment]
I didn't change any of the default settings. Where would the `formatoptions` setting be located?

I just commented out everything in my ~/.vimrc file (except the code that executes pathogen), and the feature still doesn't work. However, what does work is, when I start the `/**` comment, the next line will start off with a space.

**Comment by ches** [comment]
@hlin117 vim-scala sets `formatoptions` [here][1]. You can see we set options such as `r` and `o` which relate to this subject, those are described [here][2].

Nope, not having any issue with this here, it works exactly as you want including the closing `/` automatically removing the space. The only difference is that we don't use the recommended Scaladoc-style alignment, i.e. instead of

```
/**
  * Comment
  */
```

We use:

```
/**
 * Comment
 */
```

I think this was just @derekwyatt's choice that's been this way in the plugin for awhile. Personally I hardly ever see open source Scala projects that follow the unusual Scaladoc alignment recommendation, so I've never minded. You can probably customize this by setting a custom value for the `comments` option if you prefer the Scaladoc way or if its a project or organizational standard you need to work with.

[1]: https://github.com/derekwyatt/vim-scala/blob/71ada50fc5e2b3c9fdbdb75835a218d2c245efec/ftplugin/scala.vim#L13-L15
[2]: http://vimdoc.sourceforge.net/htmldoc/change.html#fo-table

**Comment by derekwyatt** [comment]
OK, then I don't think it has anything to do with this plugin.  I would recommend that you type `:set formatoptions` once everything's loaded just to make sure that it's set the way it's supposed to be set; you might have another plugin messing with things.

**Comment by hlin117** [comment]
If I figure out what plugin it is, should I open up another issue for the
sake of package compatibility?

On Mon, Sep 21, 2015 at 1:22 AM, Derek Wyatt <notifications@github.com>
wrote:

> OK, then I don't think it has anything to do with this plugin. I would
> recommend that you type :set formatoptions once everything's loaded just
> to make sure that it's set the way it's supposed to be set; you might have
> another plugin messing with things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_derekwyatt_vim-2Dscala_issues_112-23issuecomment-2D141886045&d=AwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=IgVP_sCIQHhgRgxQoo7gufqSQOvlFIckTGgYIpXBa_4&m=xfBD429Rim_10nuMOdFGHrr-V3Mfz6p-K_dl8ywj55I&s=3Z8JosAiBH3LYFQ25cJcRIDA_xuREhdPDmw7cazbe2E&e=>
> .
>



-- 



*Henry Lin, Research AssistantM.S. Computer ScienceUniversity of Illinois
at Urbana-Champaign 2016847-769-8729 | halin2@illinois.edu
<halin2@illinois.edu>*

**Comment by derekwyatt** [comment]
Nope. There's nothing we can do about it. Overriding the settings we put in is a design feature of Vim. If disallowed it / warned on it, that would be a bad thing.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Henry LinSent: Monday, September 21, 2015 10:55 AMTo: derekwyatt/vim-scalaReply To: derekwyatt/vim-scalaCc: Derek WyattSubject: Re: [vim-scala] Autogenerating multilined comments (#112)If I figure out what plugin it is, should I open up another issue for the
sake of package compatibility?

On Mon, Sep 21, 2015 at 1:22 AM, Derek Wyatt <notifications@github.com>
wrote:

> OK, then I don't think it has anything to do with this plugin. I would
> recommend that you type :set formatoptions once everything's loaded just
> to make sure that it's set the way it's supposed to be set; you might have
> another plugin messing with things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_derekwyatt_vim-2Dscala_issues_112-23issuecomment-2D141886045&d=AwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=IgVP_sCIQHhgRgxQoo7gufqSQOvlFIckTGgYIpXBa_4&m=xfBD429Rim_10nuMOdFGHrr-V3Mfz6p-K_dl8ywj55I&s=3Z8JosAiBH3LYFQ25cJcRIDA_xuREhdPDmw7cazbe2E&e=>
> .
>



-- 



*Henry Lin, Research AssistantM.S. Computer ScienceUniversity of Illinois
at Urbana-Champaign 2016847-769-8729 | halin2@illinois.edu
<halin2@illinois.edu>*


—Reply to this email directly or view it on GitHub.

**Comment by ches** [comment]
If something else is clobbering your `formatoptions`, it's probably a plugin that isn't using `setlocal` for it. That's a bug you can report to whatever plugin is doing that :wink:
