### ISSUE TITLE
CSV variables are not syntax-highlighted as expected.

### ISSUE THREAD

**Issue by aa8y** [derekwyatt/vim-scala#120]
When we have a CSV of variables, only the first variable is highlighted, while all of them should be.

<img width="218" alt="screen shot 2016-01-25 at 1 39 40 pm" src="https://cloud.githubusercontent.com/assets/5642392/12563794/302f751c-c369-11e5-97d1-a60ac2ead6b0.png">

**Comment by derekwyatt** [comment]
That oughta fix it.
