### ISSUE TITLE
“syn include @scalaHtml syntax/html.vim” conflicts with standard help

### ISSUE THREAD

**Issue by neowit** [derekwyatt/vim-scala#122]
Environment: MacVim 7.4 (Included patches: 1-1090), from homebrew.
With `vim-scala` plugin installed any attempt to open standard help, e.g. `:h help`
results in this error:
```
"helphelp.txt" [readonly] 354L, 13782C
Error detected while processing /usr/local/Cellar/macvim/7.4-91/MacVim.app/Contents/Resources/vim/runtime/syntax/html.vim:
line  210:
E492: Not an editor command:   HtmlHiLink htmlStyleArg htmlString
line  213:
E121: Undefined variable: main_syntax
E15: Invalid expression: main_syntax == "html"
line  228:
E492: Not an editor command:   HtmlHiLink htmlTag                     Function
line  290:
E184: No such user-defined command: HtmlHiLink
line  294:
E121: Undefined variable: main_syntax
E15: Invalid expression: main_syntax == 'html'
line  298:
E121: Undefined variable: s:cpo_save
E15: Invalid expression: s:cpo_save
line  299:
E108: No such variable: "s:cpo_save"
Error detected while processing /Users/andrey/Dropbox/ApplicationSettings/vim/bundle/vim-scala/syntax/scala.vim:
line  219:
E121: Undefined variable: main_syntax
E15: Invalid expression: main_syntax ==# 'scala'
```
With `vim-scala` plugin removed help opens as expected without issues.

the culprit appears to be [line 35](https://github.com/derekwyatt/vim-scala/blob/3f85f50181259fc89f992d0c58bba3ca9a7c6899/syntax/scala.vim#L35) in syntax/scala/vim
```vim
syn include @scalaHtml syntax/html.vim
```

if I comment it out or replace with 
```vim
exe 'syn include @scalaHtml $VIMRUNTIME' . '/syntax/html.vim' 
```
then the error goes away.

**Comment by neowit** [comment]
actually, after further testing it turns out that 
```vim
exe 'syn include @scalaHtml $VIMRUNTIME' . '/syntax/html.vim' 
```
does not actually fix the problem.  
The only way (I found) to make the error go away is to remove [line 35](https://github.com/derekwyatt/vim-scala/blob/3f85f50181259fc89f992d0c58bba3ca9a7c6899/syntax/scala.vim#L35).

**Comment by derekwyatt** [comment]
Hopefully 842baaff633b61fcc92e1db10042f0ed9571cf95 fixes it.  Can't test it from where I am right now.

**Comment by neowit** [comment]
Yes, it does seem to have fixed the issue.
Thank you.
