### ISSUE TITLE
Suffix .sc is not supported

### ISSUE THREAD

**Issue by kuchaguangjie** [derekwyatt/vim-scala#132]
If I name a scala source code with suffix `.sc`, then vim-scala won't highlight it, how to fix that, thanks.

**Comment by kuchaguangjie** [comment]
I just found a solution by viewing the source code in my machine,

just need to add a line in `vim-scala/ftdetect/scala.vim`

`au BufRead,BufNewFile *.sc set filetype=scala`

Maybe, it's better to merge that into the source code :)

**Comment by ches** [comment]
I've not seen this to be a common convention so I don't know if we'd add it to the plugin proper, but if you'd like to support it in your personal configuration you should be able to add something like this to your vimrc:

```vim
autocmd BufRead,BufNewFile *.sc set filetype=scala
```

**Comment by kuchaguangjie** [comment]
@ches I am very new to scala, but on wikipedia [scala page](https://en.wikipedia.org/wiki/Scala_%28programming_language%29), it says file name is `.scala` or `.sc`. So, I guess the plugin should support that by default, because 1) it's much shorter, 2) no body else use `.sc`.
