### ISSUE TITLE
Integration into Vim runtime

### ISSUE THREAD

**Issue by Petesta** [derekwyatt/vim-scala#133]
Hello, I was looking to see if it was possible to include the syntax script for Scala highlighting in Vim distributions by default, especially with the upcoming release of Vim 8. Other JVM languages such as Clojure and Java have already found their way onto Vim's runtime path and I think it would be great if Scala did as well.

I've contacted the maintainers of Vim and opened an [issue](https://github.com/vim/vim/issues/907)  to get the file merged in.

Assuming you were ok with this and like to have it integrated, we would need to get all the necessary files to [Bram](https://github.com/brammool).

Last step would be to figure out the dual licenses since `vim-scala` uses Apache but I don't think that should be a problem.

What do you think?

**Comment by derekwyatt** [comment]
Works for me. We can switch the license to whatever makes things easier.

**Comment by Petesta** [comment]
Awesome, will ping them about this and keep you in the loop.

**Comment by ches** [comment]
My quick thoughts:

- The `ftdetect` certainly belongs in the core Vim distribution if the syntax file does, probably no controversy there.
- `indent` probably should go in core too. I think Derek wasn't the original author so may need to check license clearance there.
- Need to double-check that error formats and stuff are still in good working order but `compiler` is probably good to include too. @derekwyatt is there anything that would be appropriate to merge from vim-sbt?
- `plugin` stuff of course does not belong.
- The main `ftplugin` file has some settings that are nearly ubiquitous Scala formatting standards, they could make sense to include but FuzzyFinder-related code needs to be pulled out of there and could go to `autoload` in this project.

Both the syntax and indent have weaknesses but hopefully they'll get more exposure and people will submit improvements back here. See how projects like [vim-ruby][1] track updates for runtime files in between Vim releases and submit them upstream.

[1]: https://github.com/vim-ruby/vim-ruby

**Comment by derekwyatt** [comment]
I'm not super happy with `vim-sbt` and don't really use it.  I think we're on the same page about what to include though... essentially, anything that requires a plugin is out.  There are other "derekisms" in there that shouldn't be as well.

**Comment by Petesta** [comment]
I've opened a [PR](https://github.com/vim/vim/pull/988) against Vim to integrate into the runtime. Are these all the files we'd like to include? Any to exclude?

Also, can we relicense some of these files to be compatible with Vim?

**Comment by derekwyatt** [comment]
Yup.  I'm going to put some time aside this weekend to do this.  Thanks for pushing it forward.

**Comment by Petesta** [comment]
Lol, I was just typing out a message for this. Quick response! 😄 

Sweet! Thanks for that!
