### ISSUE TITLE
[Hightlight] Add Chisel keyword support

### ISSUE THREAD

**Issue by dpretet** [derekwyatt/vim-scala#158]
Hello Derek,

I am using nowadays, more specifically [Chisel](https://github.com/freechipsproject/chisel3), a DSL for hardware design. Your plugin is very good, thanks for your work 🤓. I just miss two keywords:

* elsewhen
* otherwise

Would you mind to add them for highlighting ?

**Comment by ches** [comment]
Hi, old question here, but:

Vim has an idiom of [compound (dotted) filetypes](https://vi.stackexchange.com/questions/4940/where-are-vim-compound-dotted-filetypes-documented) that can often work well for dialects and DSLs, we even use it here for [vim-sbt] to complement vim-scala.

I think you could create a small plugin to extend `syntax/scala.vim` for a `chisel.scala` filetype much like vim-sbt does.

Personally I'm not familiar with Chisel, so I think such a mini plugin would be best supported/maintained by someone who is.

[vim-sbt]: https://github.com/derekwyatt/vim-sbt
