### ISSUE TITLE
Setting `compiler sbt` stops the quick fix window from opening

### ISSUE THREAD

**Issue by matteematt** [derekwyatt/vim-scala#162]
I am not sure if this is the correct place to ask this but I have had an issue today where I have not been able to read in an error file into the quick fix menu when a Scala file is open in a buffer. I have tracked it down to the line `compiler sbt` in `ftplugin/scala.vim`, when I comment that line out the quickfix window then works as expected. I am happy to leave it commented out, but I was wondering if anyone would know why this issue would occur?

**Comment by benknoble** [comment]
Compiler scripts often set the errorformat. If that doesn't match your error file, that can be an issue. However, it is usually a local option, so it shouldn't affect other buffers (unless set globally)

**Comment by matteematt** [comment]
Ok that makes sense. I can just leave it commented out for now so it doesn't interfere with my errorformat. Thanks for the reply
