### ISSUE TITLE
Should not have ftdetect for sbt file

### ISSUE THREAD

**Issue by vheon** [derekwyatt/vim-scala#54]
I have [vim-sbt](https://github.com/derekwyatt/vim-sbt) installed but if it is load before vim-scala then *.sbt will have the `scala` filetype and the syntax highlighting will be wrong.

**Comment by ches** [comment]
Seems like it would make sense if vim-scala's ftdetect changed from:

```vim
au BufRead,BufNewFile *.scala,*.sbt set filetype=scala
```

to:

```vim
au BufRead,BufNewFile *.scala set filetype=scala
au BufRead,BufNewFile *.sbt setfiletype scala
```

The `setfiletype` form will not change it if already set by something loaded earlier. That should continue to work well for people that only have vim-scala installed. Maybe you can submit a PR?

Further, it might be nice if vim-sbt did `set filetype=sbt.scala`. I'd probably like my regular Scala snippets, abbreviations, whatever to work in sbt files if I used vim-sbt. But that's another matter :grin:

**Comment by ches** [comment]
I've applied this fix, the extra syntax highlighting from vim-sbt should now work if you have it installed.

Keep an eye on derekwyatt/vim-sbt#2 also, but you should still get the sbt syntax highlighting showing up with or without that change merged once you've updated to the latest vim-scala.
