### ISSUE TITLE
Spell check does not work for comments

### ISSUE THREAD

**Issue by blacklab** [derekwyatt/vim-scala#55]
Hi,

I wanted to use Vim's spell checker for my Scala code. It did not work until I changed this line in the syntax file:

    syn region scalaDocComment start="/\*\*" end="\*/"  contains=scalaDocTags,scalaTodo,@scalaHtml,@Spell keepend

I don't know if this is clean. However, it would be nice if the syntax file would be changed to support spell checking in the comments.

**Comment by derekwyatt** [comment]
Closed thanks to @ches
