### ISSUE TITLE
Can't get it work with Vundle

### ISSUE THREAD

**Issue by katcipis** [derekwyatt/vim-scala#75]
Hi,

This is probably some silly mistake that I am making, but I'm trying to install the plugin with Vundle:

https://github.com/katcipis/my.vim/blob/master/vimrc#L73

And no magic happens :-(. I can see the plugin installed on my ~/.vim, but when I open a File.scala there is no syntax highlighting, nothing. Is there something else that I have to do get it working ?

I executed the Vundle install command, actually all the others plugins that I have are working, except vim-scala.

**Comment by ches** [comment]
Can anyone report if you're still having this issue with up-to-date vim-scala and Vundle?

There's nothing very unusual about the ftdetect and it's working fine with other plugin managers, not something that seems reproducible.

**Comment by paramadeep** [comment]
I'm facing this issue, I've latest of all.

**Comment by ches** [comment]
@paramadeep I just peeked at your dotfiles, assuming `paramadeep/nagal` is the correct place—your `.vimrc` is missing `filetype off` before the Vundle setup. That is required according to the Vundle README and gmarik/Vundle.vim#16. Could you add that and see if it resolves the problem?

Likewise for anyone who experienced this, you may want to confirm that config detail.

**Comment by paramadeep** [comment]
@ches it worked. My bad I missed it. Thanks a lot.

**Comment by ches** [comment]
No worries, glad that's solved it and hope that's all takes for most everyone else here too.

**Comment by jamiis** [comment]
@ches I'm still experiencing this problem. I just git pulled the latest version of vundle and insured everything was latest. `:set filetype=scala` fixes the problem on a per-open-file basis. My vimrc is [here](https://github.com/jamiis/dotfiles/blob/master/vimrc), maybe I am doing something wrong?

**Comment by ches** [comment]
@jamiis You have `filetype plugin indent on` on line 34, and again redundantly on 164-165—try removing the latter two lines. You also have `syntax on` on line 35 and and `syntax enable ` on 345. Not sure, but that might also be confusing Vim. The latter probably shouldn't be necessary.

As Derek instructed [here], the first thing we'd ask is that you minimize your config to rule out any other plugins as sources of problems. If that eliminates the issue, gradually re-enable plugins and settings until you find the culprit.

[here]: https://github.com/derekwyatt/vim-scala/issues/113#issuecomment-152843015

**Comment by jamiis** [comment]
@ches that fixed it! thank you.

**Comment by dmitrime** [comment]
doesn't work for me. even setting filetype=scala does not do anything. [vimrc](https://github.com/dmitrime/dotfiles/blob/master/vim/vimrc)

**Comment by derekwyatt** [comment]
This plugin is now part of the Vim distribution. You should just upgrade.

**Comment by dmitrime** [comment]
@derekwyatt thanks! works with vim8.
