### ISSUE TITLE
No highlighting when opening a new window

### ISSUE THREAD

**Issue by zg** [derekwyatt/vim-scala#87]
How to replicate:

    $ vim file1.scala
    <ctrl-w> s
    :e file2.scala

Outcome: No syntax highlighting for new window.
Expected: Highlighting for new window.

**Comment by derekwyatt** [comment]
That doesn't replicate the problem for me.  You gotta give me more than that.

**Comment by zg** [comment]
I'm so sorry.  There's a mistake on [this](http://bsnyderblog.blogspot.com/2012/12/vim-syntax-highlighting-for-scala-bash.html) page I stumbled upon for quickly downloading the correct files for the syntax files.  They left out a variable in the cURL call.  Here's the correct way to download all the files to their correct locations:

    mkdir -p ~/.vim/{ftdetect,indent,syntax} && for d in ftdetect indent syntax ; do curl -o ~/.vim/$d/scala.vim https://raw.githubusercontent.com/derekwyatt/vim-scala/master/$d/scala.vim; done

**Comment by derekwyatt** [comment]
Thanks for following up :)
