### ISSUE TITLE
Vim high CPU usage

### ISSUE THREAD

**Issue by dimparf** [derekwyatt/vim-scala#89]
When I open more than 8 files Vim makes heavy load on the CPU.
 If I remove the plug-in (syntax highlighting) then everything is OK.

**Comment by derekwyatt** [comment]
I regularly have _dozens_ of scala files open in Vim, never a problem.  You've got some other plugin that's the problem, and if it's related to syntax highlighting, I expect that you've got some interesting syntax-related plugin that's the problem, and by getting rid of the syntax highlighting aspect of the scala plugin, you're eliminating the problem with the other plugin.

At any rate, unless you can prove that it has something to do with the vim-scala plugin, I'm going to keep this one closed.
